global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'giropops-monitoring'
rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9100']

#  - job_name: 'netdata'
#    metrics_path: '/api/v1/allmetrics'
#    params:
#      format: [prometheus]
#    honor_labels: true
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:19999']